const PERMISSIONS = {
  SUSPEND_USERS:      "SUSPEND_USERS",
  VERIFY_PROFESSORS:  "VERIFY_PROFESSORS",
  HANDLE_REPORTS:     "HANDLE_REPORTS",
  MODERATE_CONTENT:   "MODERATE_CONTENT",
  MANAGE_ROOMS:       "MANAGE_ROOMS",
  VALIDATE_OTHER:     "VALIDATE_OTHER",
  APPROVE_RESOURCES:  "APPROVE_RESOURCES",
  DELETE_INACTIVE:    "DELETE_INACTIVE",
};

module.exports = PERMISSIONS;